/*
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.ComGithubJenkinsXJxPkgApisJenkinsIoV1AccountReference;
import org.threeten.bp.OffsetDateTime;

/**
 * UserDetails containers details of a user
 */
@ApiModel(description = "UserDetails containers details of a user")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-03-28T12:38:15.775957Z[Europe/London]")
public class ComGithubJenkinsXJxPkgApisJenkinsIoV1UserDetails {
  public static final String SERIALIZED_NAME_ACCOUNT_REFERENCE = "accountReference";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_REFERENCE)
  private List<ComGithubJenkinsXJxPkgApisJenkinsIoV1AccountReference> accountReference = null;

  public static final String SERIALIZED_NAME_AVATAR_URL = "avatarUrl";
  @SerializedName(SERIALIZED_NAME_AVATAR_URL)
  private String avatarUrl;

  public static final String SERIALIZED_NAME_CREATION_TIMESTAMP = "creationTimestamp";
  @SerializedName(SERIALIZED_NAME_CREATION_TIMESTAMP)
  private OffsetDateTime creationTimestamp;

  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  private String email;

  public static final String SERIALIZED_NAME_EXTERNAL_USER = "externalUser";
  @SerializedName(SERIALIZED_NAME_EXTERNAL_USER)
  private Boolean externalUser;

  public static final String SERIALIZED_NAME_LOGIN = "login";
  @SerializedName(SERIALIZED_NAME_LOGIN)
  private String login;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_SERVICE_ACCOUNT = "serviceAccount";
  @SerializedName(SERIALIZED_NAME_SERVICE_ACCOUNT)
  private String serviceAccount;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  private String url;

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1UserDetails accountReference(List<ComGithubJenkinsXJxPkgApisJenkinsIoV1AccountReference> accountReference) {
    this.accountReference = accountReference;
    return this;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1UserDetails addAccountReferenceItem(ComGithubJenkinsXJxPkgApisJenkinsIoV1AccountReference accountReferenceItem) {
    if (this.accountReference == null) {
      this.accountReference = new ArrayList<ComGithubJenkinsXJxPkgApisJenkinsIoV1AccountReference>();
    }
    this.accountReference.add(accountReferenceItem);
    return this;
  }

   /**
   * Get accountReference
   * @return accountReference
  **/
  @ApiModelProperty(value = "")
  public List<ComGithubJenkinsXJxPkgApisJenkinsIoV1AccountReference> getAccountReference() {
    return accountReference;
  }

  public void setAccountReference(List<ComGithubJenkinsXJxPkgApisJenkinsIoV1AccountReference> accountReference) {
    this.accountReference = accountReference;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1UserDetails avatarUrl(String avatarUrl) {
    this.avatarUrl = avatarUrl;
    return this;
  }

   /**
   * Get avatarUrl
   * @return avatarUrl
  **/
  @ApiModelProperty(value = "")
  public String getAvatarUrl() {
    return avatarUrl;
  }

  public void setAvatarUrl(String avatarUrl) {
    this.avatarUrl = avatarUrl;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1UserDetails creationTimestamp(OffsetDateTime creationTimestamp) {
    this.creationTimestamp = creationTimestamp;
    return this;
  }

   /**
   * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
   * @return creationTimestamp
  **/
  @ApiModelProperty(value = "Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.")
  public OffsetDateTime getCreationTimestamp() {
    return creationTimestamp;
  }

  public void setCreationTimestamp(OffsetDateTime creationTimestamp) {
    this.creationTimestamp = creationTimestamp;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1UserDetails email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @ApiModelProperty(value = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1UserDetails externalUser(Boolean externalUser) {
    this.externalUser = externalUser;
    return this;
  }

   /**
   * Get externalUser
   * @return externalUser
  **/
  @ApiModelProperty(value = "")
  public Boolean getExternalUser() {
    return externalUser;
  }

  public void setExternalUser(Boolean externalUser) {
    this.externalUser = externalUser;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1UserDetails login(String login) {
    this.login = login;
    return this;
  }

   /**
   * Get login
   * @return login
  **/
  @ApiModelProperty(value = "")
  public String getLogin() {
    return login;
  }

  public void setLogin(String login) {
    this.login = login;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1UserDetails name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1UserDetails serviceAccount(String serviceAccount) {
    this.serviceAccount = serviceAccount;
    return this;
  }

   /**
   * Get serviceAccount
   * @return serviceAccount
  **/
  @ApiModelProperty(value = "")
  public String getServiceAccount() {
    return serviceAccount;
  }

  public void setServiceAccount(String serviceAccount) {
    this.serviceAccount = serviceAccount;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1UserDetails url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @ApiModelProperty(value = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComGithubJenkinsXJxPkgApisJenkinsIoV1UserDetails comGithubJenkinsXJxPkgApisJenkinsIoV1UserDetails = (ComGithubJenkinsXJxPkgApisJenkinsIoV1UserDetails) o;
    return Objects.equals(this.accountReference, comGithubJenkinsXJxPkgApisJenkinsIoV1UserDetails.accountReference) &&
        Objects.equals(this.avatarUrl, comGithubJenkinsXJxPkgApisJenkinsIoV1UserDetails.avatarUrl) &&
        Objects.equals(this.creationTimestamp, comGithubJenkinsXJxPkgApisJenkinsIoV1UserDetails.creationTimestamp) &&
        Objects.equals(this.email, comGithubJenkinsXJxPkgApisJenkinsIoV1UserDetails.email) &&
        Objects.equals(this.externalUser, comGithubJenkinsXJxPkgApisJenkinsIoV1UserDetails.externalUser) &&
        Objects.equals(this.login, comGithubJenkinsXJxPkgApisJenkinsIoV1UserDetails.login) &&
        Objects.equals(this.name, comGithubJenkinsXJxPkgApisJenkinsIoV1UserDetails.name) &&
        Objects.equals(this.serviceAccount, comGithubJenkinsXJxPkgApisJenkinsIoV1UserDetails.serviceAccount) &&
        Objects.equals(this.url, comGithubJenkinsXJxPkgApisJenkinsIoV1UserDetails.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountReference, avatarUrl, creationTimestamp, email, externalUser, login, name, serviceAccount, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComGithubJenkinsXJxPkgApisJenkinsIoV1UserDetails {\n");
    
    sb.append("    accountReference: ").append(toIndentedString(accountReference)).append("\n");
    sb.append("    avatarUrl: ").append(toIndentedString(avatarUrl)).append("\n");
    sb.append("    creationTimestamp: ").append(toIndentedString(creationTimestamp)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    externalUser: ").append(toIndentedString(externalUser)).append("\n");
    sb.append("    login: ").append(toIndentedString(login)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    serviceAccount: ").append(toIndentedString(serviceAccount)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

