/*
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.ComGithubJenkinsXJxPkgApisJenkinsIoV1CoreActivityStep;
import org.threeten.bp.OffsetDateTime;

/**
 * StageActivityStep represents a stage of zero to more sub steps in a jenkins pipeline
 */
@ApiModel(description = "StageActivityStep represents a stage of zero to more sub steps in a jenkins pipeline")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-03-28T12:38:15.775957Z[Europe/London]")
public class ComGithubJenkinsXJxPkgApisJenkinsIoV1StageActivityStep {
  public static final String SERIALIZED_NAME_COMPLETED_TIMESTAMP = "completedTimestamp";
  @SerializedName(SERIALIZED_NAME_COMPLETED_TIMESTAMP)
  private OffsetDateTime completedTimestamp;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_STARTED_TIMESTAMP = "startedTimestamp";
  @SerializedName(SERIALIZED_NAME_STARTED_TIMESTAMP)
  private OffsetDateTime startedTimestamp;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public static final String SERIALIZED_NAME_STEPS = "steps";
  @SerializedName(SERIALIZED_NAME_STEPS)
  private List<ComGithubJenkinsXJxPkgApisJenkinsIoV1CoreActivityStep> steps = null;

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1StageActivityStep completedTimestamp(OffsetDateTime completedTimestamp) {
    this.completedTimestamp = completedTimestamp;
    return this;
  }

   /**
   * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
   * @return completedTimestamp
  **/
  @ApiModelProperty(value = "Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.")
  public OffsetDateTime getCompletedTimestamp() {
    return completedTimestamp;
  }

  public void setCompletedTimestamp(OffsetDateTime completedTimestamp) {
    this.completedTimestamp = completedTimestamp;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1StageActivityStep description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1StageActivityStep name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1StageActivityStep startedTimestamp(OffsetDateTime startedTimestamp) {
    this.startedTimestamp = startedTimestamp;
    return this;
  }

   /**
   * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
   * @return startedTimestamp
  **/
  @ApiModelProperty(value = "Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.")
  public OffsetDateTime getStartedTimestamp() {
    return startedTimestamp;
  }

  public void setStartedTimestamp(OffsetDateTime startedTimestamp) {
    this.startedTimestamp = startedTimestamp;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1StageActivityStep status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1StageActivityStep steps(List<ComGithubJenkinsXJxPkgApisJenkinsIoV1CoreActivityStep> steps) {
    this.steps = steps;
    return this;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1StageActivityStep addStepsItem(ComGithubJenkinsXJxPkgApisJenkinsIoV1CoreActivityStep stepsItem) {
    if (this.steps == null) {
      this.steps = new ArrayList<ComGithubJenkinsXJxPkgApisJenkinsIoV1CoreActivityStep>();
    }
    this.steps.add(stepsItem);
    return this;
  }

   /**
   * Get steps
   * @return steps
  **/
  @ApiModelProperty(value = "")
  public List<ComGithubJenkinsXJxPkgApisJenkinsIoV1CoreActivityStep> getSteps() {
    return steps;
  }

  public void setSteps(List<ComGithubJenkinsXJxPkgApisJenkinsIoV1CoreActivityStep> steps) {
    this.steps = steps;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComGithubJenkinsXJxPkgApisJenkinsIoV1StageActivityStep comGithubJenkinsXJxPkgApisJenkinsIoV1StageActivityStep = (ComGithubJenkinsXJxPkgApisJenkinsIoV1StageActivityStep) o;
    return Objects.equals(this.completedTimestamp, comGithubJenkinsXJxPkgApisJenkinsIoV1StageActivityStep.completedTimestamp) &&
        Objects.equals(this.description, comGithubJenkinsXJxPkgApisJenkinsIoV1StageActivityStep.description) &&
        Objects.equals(this.name, comGithubJenkinsXJxPkgApisJenkinsIoV1StageActivityStep.name) &&
        Objects.equals(this.startedTimestamp, comGithubJenkinsXJxPkgApisJenkinsIoV1StageActivityStep.startedTimestamp) &&
        Objects.equals(this.status, comGithubJenkinsXJxPkgApisJenkinsIoV1StageActivityStep.status) &&
        Objects.equals(this.steps, comGithubJenkinsXJxPkgApisJenkinsIoV1StageActivityStep.steps);
  }

  @Override
  public int hashCode() {
    return Objects.hash(completedTimestamp, description, name, startedTimestamp, status, steps);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComGithubJenkinsXJxPkgApisJenkinsIoV1StageActivityStep {\n");
    
    sb.append("    completedTimestamp: ").append(toIndentedString(completedTimestamp)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    startedTimestamp: ").append(toIndentedString(startedTimestamp)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    steps: ").append(toIndentedString(steps)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

