/*
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.ComGithubJenkinsXJxPkgApisJenkinsIoV1EnvironmentRepository;
import org.openapitools.client.model.ComGithubJenkinsXJxPkgApisJenkinsIoV1PreviewGitSpec;
import org.openapitools.client.model.ComGithubJenkinsXJxPkgApisJenkinsIoV1TeamSettings;

/**
 * EnvironmentSpec is the specification of an Environment
 */
@ApiModel(description = "EnvironmentSpec is the specification of an Environment")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-03-28T12:38:15.775957Z[Europe/London]")
public class ComGithubJenkinsXJxPkgApisJenkinsIoV1EnvironmentSpec {
  public static final String SERIALIZED_NAME_CLUSTER = "cluster";
  @SerializedName(SERIALIZED_NAME_CLUSTER)
  private String cluster;

  public static final String SERIALIZED_NAME_KIND = "kind";
  @SerializedName(SERIALIZED_NAME_KIND)
  private String kind;

  public static final String SERIALIZED_NAME_LABEL = "label";
  @SerializedName(SERIALIZED_NAME_LABEL)
  private String label;

  public static final String SERIALIZED_NAME_NAMESPACE = "namespace";
  @SerializedName(SERIALIZED_NAME_NAMESPACE)
  private String namespace;

  public static final String SERIALIZED_NAME_ORDER = "order";
  @SerializedName(SERIALIZED_NAME_ORDER)
  private Integer order;

  public static final String SERIALIZED_NAME_PREVIEW_GIT_INFO = "previewGitInfo";
  @SerializedName(SERIALIZED_NAME_PREVIEW_GIT_INFO)
  private ComGithubJenkinsXJxPkgApisJenkinsIoV1PreviewGitSpec previewGitInfo = null;

  public static final String SERIALIZED_NAME_PROMOTION_STRATEGY = "promotionStrategy";
  @SerializedName(SERIALIZED_NAME_PROMOTION_STRATEGY)
  private String promotionStrategy;

  public static final String SERIALIZED_NAME_PULL_REQUEST_U_R_L = "pullRequestURL";
  @SerializedName(SERIALIZED_NAME_PULL_REQUEST_U_R_L)
  private String pullRequestURL;

  public static final String SERIALIZED_NAME_SOURCE = "source";
  @SerializedName(SERIALIZED_NAME_SOURCE)
  private ComGithubJenkinsXJxPkgApisJenkinsIoV1EnvironmentRepository source = null;

  public static final String SERIALIZED_NAME_TEAM_SETTINGS = "teamSettings";
  @SerializedName(SERIALIZED_NAME_TEAM_SETTINGS)
  private ComGithubJenkinsXJxPkgApisJenkinsIoV1TeamSettings teamSettings = null;

  public static final String SERIALIZED_NAME_WEB_HOOK_ENGINE = "webHookEngine";
  @SerializedName(SERIALIZED_NAME_WEB_HOOK_ENGINE)
  private String webHookEngine;

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1EnvironmentSpec cluster(String cluster) {
    this.cluster = cluster;
    return this;
  }

   /**
   * Get cluster
   * @return cluster
  **/
  @ApiModelProperty(value = "")
  public String getCluster() {
    return cluster;
  }

  public void setCluster(String cluster) {
    this.cluster = cluster;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1EnvironmentSpec kind(String kind) {
    this.kind = kind;
    return this;
  }

   /**
   * Get kind
   * @return kind
  **/
  @ApiModelProperty(value = "")
  public String getKind() {
    return kind;
  }

  public void setKind(String kind) {
    this.kind = kind;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1EnvironmentSpec label(String label) {
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  @ApiModelProperty(value = "")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1EnvironmentSpec namespace(String namespace) {
    this.namespace = namespace;
    return this;
  }

   /**
   * Get namespace
   * @return namespace
  **/
  @ApiModelProperty(value = "")
  public String getNamespace() {
    return namespace;
  }

  public void setNamespace(String namespace) {
    this.namespace = namespace;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1EnvironmentSpec order(Integer order) {
    this.order = order;
    return this;
  }

   /**
   * Get order
   * @return order
  **/
  @ApiModelProperty(value = "")
  public Integer getOrder() {
    return order;
  }

  public void setOrder(Integer order) {
    this.order = order;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1EnvironmentSpec previewGitInfo(ComGithubJenkinsXJxPkgApisJenkinsIoV1PreviewGitSpec previewGitInfo) {
    this.previewGitInfo = previewGitInfo;
    return this;
  }

   /**
   * Get previewGitInfo
   * @return previewGitInfo
  **/
  @ApiModelProperty(value = "")
  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PreviewGitSpec getPreviewGitInfo() {
    return previewGitInfo;
  }

  public void setPreviewGitInfo(ComGithubJenkinsXJxPkgApisJenkinsIoV1PreviewGitSpec previewGitInfo) {
    this.previewGitInfo = previewGitInfo;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1EnvironmentSpec promotionStrategy(String promotionStrategy) {
    this.promotionStrategy = promotionStrategy;
    return this;
  }

   /**
   * Get promotionStrategy
   * @return promotionStrategy
  **/
  @ApiModelProperty(value = "")
  public String getPromotionStrategy() {
    return promotionStrategy;
  }

  public void setPromotionStrategy(String promotionStrategy) {
    this.promotionStrategy = promotionStrategy;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1EnvironmentSpec pullRequestURL(String pullRequestURL) {
    this.pullRequestURL = pullRequestURL;
    return this;
  }

   /**
   * Get pullRequestURL
   * @return pullRequestURL
  **/
  @ApiModelProperty(value = "")
  public String getPullRequestURL() {
    return pullRequestURL;
  }

  public void setPullRequestURL(String pullRequestURL) {
    this.pullRequestURL = pullRequestURL;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1EnvironmentSpec source(ComGithubJenkinsXJxPkgApisJenkinsIoV1EnvironmentRepository source) {
    this.source = source;
    return this;
  }

   /**
   * Get source
   * @return source
  **/
  @ApiModelProperty(value = "")
  public ComGithubJenkinsXJxPkgApisJenkinsIoV1EnvironmentRepository getSource() {
    return source;
  }

  public void setSource(ComGithubJenkinsXJxPkgApisJenkinsIoV1EnvironmentRepository source) {
    this.source = source;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1EnvironmentSpec teamSettings(ComGithubJenkinsXJxPkgApisJenkinsIoV1TeamSettings teamSettings) {
    this.teamSettings = teamSettings;
    return this;
  }

   /**
   * Get teamSettings
   * @return teamSettings
  **/
  @ApiModelProperty(value = "")
  public ComGithubJenkinsXJxPkgApisJenkinsIoV1TeamSettings getTeamSettings() {
    return teamSettings;
  }

  public void setTeamSettings(ComGithubJenkinsXJxPkgApisJenkinsIoV1TeamSettings teamSettings) {
    this.teamSettings = teamSettings;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1EnvironmentSpec webHookEngine(String webHookEngine) {
    this.webHookEngine = webHookEngine;
    return this;
  }

   /**
   * Get webHookEngine
   * @return webHookEngine
  **/
  @ApiModelProperty(value = "")
  public String getWebHookEngine() {
    return webHookEngine;
  }

  public void setWebHookEngine(String webHookEngine) {
    this.webHookEngine = webHookEngine;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComGithubJenkinsXJxPkgApisJenkinsIoV1EnvironmentSpec comGithubJenkinsXJxPkgApisJenkinsIoV1EnvironmentSpec = (ComGithubJenkinsXJxPkgApisJenkinsIoV1EnvironmentSpec) o;
    return Objects.equals(this.cluster, comGithubJenkinsXJxPkgApisJenkinsIoV1EnvironmentSpec.cluster) &&
        Objects.equals(this.kind, comGithubJenkinsXJxPkgApisJenkinsIoV1EnvironmentSpec.kind) &&
        Objects.equals(this.label, comGithubJenkinsXJxPkgApisJenkinsIoV1EnvironmentSpec.label) &&
        Objects.equals(this.namespace, comGithubJenkinsXJxPkgApisJenkinsIoV1EnvironmentSpec.namespace) &&
        Objects.equals(this.order, comGithubJenkinsXJxPkgApisJenkinsIoV1EnvironmentSpec.order) &&
        Objects.equals(this.previewGitInfo, comGithubJenkinsXJxPkgApisJenkinsIoV1EnvironmentSpec.previewGitInfo) &&
        Objects.equals(this.promotionStrategy, comGithubJenkinsXJxPkgApisJenkinsIoV1EnvironmentSpec.promotionStrategy) &&
        Objects.equals(this.pullRequestURL, comGithubJenkinsXJxPkgApisJenkinsIoV1EnvironmentSpec.pullRequestURL) &&
        Objects.equals(this.source, comGithubJenkinsXJxPkgApisJenkinsIoV1EnvironmentSpec.source) &&
        Objects.equals(this.teamSettings, comGithubJenkinsXJxPkgApisJenkinsIoV1EnvironmentSpec.teamSettings) &&
        Objects.equals(this.webHookEngine, comGithubJenkinsXJxPkgApisJenkinsIoV1EnvironmentSpec.webHookEngine);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cluster, kind, label, namespace, order, previewGitInfo, promotionStrategy, pullRequestURL, source, teamSettings, webHookEngine);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComGithubJenkinsXJxPkgApisJenkinsIoV1EnvironmentSpec {\n");
    
    sb.append("    cluster: ").append(toIndentedString(cluster)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    namespace: ").append(toIndentedString(namespace)).append("\n");
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("    previewGitInfo: ").append(toIndentedString(previewGitInfo)).append("\n");
    sb.append("    promotionStrategy: ").append(toIndentedString(promotionStrategy)).append("\n");
    sb.append("    pullRequestURL: ").append(toIndentedString(pullRequestURL)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    teamSettings: ").append(toIndentedString(teamSettings)).append("\n");
    sb.append("    webHookEngine: ").append(toIndentedString(webHookEngine)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

