/*
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionRepositoryReference;

/**
 * ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionRepositoryReferenceList
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-03-28T12:38:15.775957Z[Europe/London]")
public class ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionRepositoryReferenceList {
  public static final String SERIALIZED_NAME_REPOSITORIES = "repositories";
  @SerializedName(SERIALIZED_NAME_REPOSITORIES)
  private List<ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionRepositoryReference> repositories = null;

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionRepositoryReferenceList repositories(List<ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionRepositoryReference> repositories) {
    this.repositories = repositories;
    return this;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionRepositoryReferenceList addRepositoriesItem(ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionRepositoryReference repositoriesItem) {
    if (this.repositories == null) {
      this.repositories = new ArrayList<ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionRepositoryReference>();
    }
    this.repositories.add(repositoriesItem);
    return this;
  }

   /**
   * Get repositories
   * @return repositories
  **/
  @ApiModelProperty(value = "")
  public List<ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionRepositoryReference> getRepositories() {
    return repositories;
  }

  public void setRepositories(List<ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionRepositoryReference> repositories) {
    this.repositories = repositories;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionRepositoryReferenceList comGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionRepositoryReferenceList = (ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionRepositoryReferenceList) o;
    return Objects.equals(this.repositories, comGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionRepositoryReferenceList.repositories);
  }

  @Override
  public int hashCode() {
    return Objects.hash(repositories);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionRepositoryReferenceList {\n");
    
    sb.append("    repositories: ").append(toIndentedString(repositories)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

