/*
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * PreviewActivityStep is the step of creating a preview environment as part of a Pull Request pipeline
 */
@ApiModel(description = "PreviewActivityStep is the step of creating a preview environment as part of a Pull Request pipeline")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-03-28T12:38:15.775957Z[Europe/London]")
public class ComGithubJenkinsXJxPkgApisJenkinsIoV1PreviewActivityStep {
  public static final String SERIALIZED_NAME_APPLICATION_U_R_L = "applicationURL";
  @SerializedName(SERIALIZED_NAME_APPLICATION_U_R_L)
  private String applicationURL;

  public static final String SERIALIZED_NAME_COMPLETED_TIMESTAMP = "completedTimestamp";
  @SerializedName(SERIALIZED_NAME_COMPLETED_TIMESTAMP)
  private OffsetDateTime completedTimestamp;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_ENVIRONMENT = "environment";
  @SerializedName(SERIALIZED_NAME_ENVIRONMENT)
  private String environment;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_PULL_REQUEST_U_R_L = "pullRequestURL";
  @SerializedName(SERIALIZED_NAME_PULL_REQUEST_U_R_L)
  private String pullRequestURL;

  public static final String SERIALIZED_NAME_STARTED_TIMESTAMP = "startedTimestamp";
  @SerializedName(SERIALIZED_NAME_STARTED_TIMESTAMP)
  private OffsetDateTime startedTimestamp;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PreviewActivityStep applicationURL(String applicationURL) {
    this.applicationURL = applicationURL;
    return this;
  }

   /**
   * Get applicationURL
   * @return applicationURL
  **/
  @ApiModelProperty(value = "")
  public String getApplicationURL() {
    return applicationURL;
  }

  public void setApplicationURL(String applicationURL) {
    this.applicationURL = applicationURL;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PreviewActivityStep completedTimestamp(OffsetDateTime completedTimestamp) {
    this.completedTimestamp = completedTimestamp;
    return this;
  }

   /**
   * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
   * @return completedTimestamp
  **/
  @ApiModelProperty(value = "Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.")
  public OffsetDateTime getCompletedTimestamp() {
    return completedTimestamp;
  }

  public void setCompletedTimestamp(OffsetDateTime completedTimestamp) {
    this.completedTimestamp = completedTimestamp;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PreviewActivityStep description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PreviewActivityStep environment(String environment) {
    this.environment = environment;
    return this;
  }

   /**
   * Get environment
   * @return environment
  **/
  @ApiModelProperty(value = "")
  public String getEnvironment() {
    return environment;
  }

  public void setEnvironment(String environment) {
    this.environment = environment;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PreviewActivityStep name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PreviewActivityStep pullRequestURL(String pullRequestURL) {
    this.pullRequestURL = pullRequestURL;
    return this;
  }

   /**
   * Get pullRequestURL
   * @return pullRequestURL
  **/
  @ApiModelProperty(value = "")
  public String getPullRequestURL() {
    return pullRequestURL;
  }

  public void setPullRequestURL(String pullRequestURL) {
    this.pullRequestURL = pullRequestURL;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PreviewActivityStep startedTimestamp(OffsetDateTime startedTimestamp) {
    this.startedTimestamp = startedTimestamp;
    return this;
  }

   /**
   * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
   * @return startedTimestamp
  **/
  @ApiModelProperty(value = "Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.")
  public OffsetDateTime getStartedTimestamp() {
    return startedTimestamp;
  }

  public void setStartedTimestamp(OffsetDateTime startedTimestamp) {
    this.startedTimestamp = startedTimestamp;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PreviewActivityStep status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComGithubJenkinsXJxPkgApisJenkinsIoV1PreviewActivityStep comGithubJenkinsXJxPkgApisJenkinsIoV1PreviewActivityStep = (ComGithubJenkinsXJxPkgApisJenkinsIoV1PreviewActivityStep) o;
    return Objects.equals(this.applicationURL, comGithubJenkinsXJxPkgApisJenkinsIoV1PreviewActivityStep.applicationURL) &&
        Objects.equals(this.completedTimestamp, comGithubJenkinsXJxPkgApisJenkinsIoV1PreviewActivityStep.completedTimestamp) &&
        Objects.equals(this.description, comGithubJenkinsXJxPkgApisJenkinsIoV1PreviewActivityStep.description) &&
        Objects.equals(this.environment, comGithubJenkinsXJxPkgApisJenkinsIoV1PreviewActivityStep.environment) &&
        Objects.equals(this.name, comGithubJenkinsXJxPkgApisJenkinsIoV1PreviewActivityStep.name) &&
        Objects.equals(this.pullRequestURL, comGithubJenkinsXJxPkgApisJenkinsIoV1PreviewActivityStep.pullRequestURL) &&
        Objects.equals(this.startedTimestamp, comGithubJenkinsXJxPkgApisJenkinsIoV1PreviewActivityStep.startedTimestamp) &&
        Objects.equals(this.status, comGithubJenkinsXJxPkgApisJenkinsIoV1PreviewActivityStep.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(applicationURL, completedTimestamp, description, environment, name, pullRequestURL, startedTimestamp, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComGithubJenkinsXJxPkgApisJenkinsIoV1PreviewActivityStep {\n");
    
    sb.append("    applicationURL: ").append(toIndentedString(applicationURL)).append("\n");
    sb.append("    completedTimestamp: ").append(toIndentedString(completedTimestamp)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    environment: ").append(toIndentedString(environment)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    pullRequestURL: ").append(toIndentedString(pullRequestURL)).append("\n");
    sb.append("    startedTimestamp: ").append(toIndentedString(startedTimestamp)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

