/*
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ExtensionParameter describes a parameter definition for an extension
 */
@ApiModel(description = "ExtensionParameter describes a parameter definition for an extension")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-03-28T12:38:15.775957Z[Europe/London]")
public class ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionParameter {
  public static final String SERIALIZED_NAME_DEFAULT_VALUE = "defaultValue";
  @SerializedName(SERIALIZED_NAME_DEFAULT_VALUE)
  private String defaultValue;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_ENVIRONMENT_VARIABLE_NAME = "environmentVariableName";
  @SerializedName(SERIALIZED_NAME_ENVIRONMENT_VARIABLE_NAME)
  private String environmentVariableName;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionParameter defaultValue(String defaultValue) {
    this.defaultValue = defaultValue;
    return this;
  }

   /**
   * Get defaultValue
   * @return defaultValue
  **/
  @ApiModelProperty(value = "")
  public String getDefaultValue() {
    return defaultValue;
  }

  public void setDefaultValue(String defaultValue) {
    this.defaultValue = defaultValue;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionParameter description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionParameter environmentVariableName(String environmentVariableName) {
    this.environmentVariableName = environmentVariableName;
    return this;
  }

   /**
   * Get environmentVariableName
   * @return environmentVariableName
  **/
  @ApiModelProperty(value = "")
  public String getEnvironmentVariableName() {
    return environmentVariableName;
  }

  public void setEnvironmentVariableName(String environmentVariableName) {
    this.environmentVariableName = environmentVariableName;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionParameter name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionParameter comGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionParameter = (ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionParameter) o;
    return Objects.equals(this.defaultValue, comGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionParameter.defaultValue) &&
        Objects.equals(this.description, comGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionParameter.description) &&
        Objects.equals(this.environmentVariableName, comGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionParameter.environmentVariableName) &&
        Objects.equals(this.name, comGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionParameter.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(defaultValue, description, environmentVariableName, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionParameter {\n");
    
    sb.append("    defaultValue: ").append(toIndentedString(defaultValue)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    environmentVariableName: ").append(toIndentedString(environmentVariableName)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

