/*
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Measurement is a percentage or a count, something measured that the system will capture within a fact
 */
@ApiModel(description = "Measurement is a percentage or a count, something measured that the system will capture within a fact")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-03-28T12:38:15.775957Z[Europe/London]")
public class ComGithubJenkinsXJxPkgApisJenkinsIoV1Measurement {
  public static final String SERIALIZED_NAME_MEASUREMENT_TYPE = "measurementType";
  @SerializedName(SERIALIZED_NAME_MEASUREMENT_TYPE)
  private String measurementType;

  public static final String SERIALIZED_NAME_MEASUREMENT_VALUE = "measurementValue";
  @SerializedName(SERIALIZED_NAME_MEASUREMENT_VALUE)
  private Integer measurementValue;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_TAGS = "tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  private List<String> tags = null;

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1Measurement measurementType(String measurementType) {
    this.measurementType = measurementType;
    return this;
  }

   /**
   * Get measurementType
   * @return measurementType
  **/
  @ApiModelProperty(required = true, value = "")
  public String getMeasurementType() {
    return measurementType;
  }

  public void setMeasurementType(String measurementType) {
    this.measurementType = measurementType;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1Measurement measurementValue(Integer measurementValue) {
    this.measurementValue = measurementValue;
    return this;
  }

   /**
   * Get measurementValue
   * @return measurementValue
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getMeasurementValue() {
    return measurementValue;
  }

  public void setMeasurementValue(Integer measurementValue) {
    this.measurementValue = measurementValue;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1Measurement name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1Measurement tags(List<String> tags) {
    this.tags = tags;
    return this;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1Measurement addTagsItem(String tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<String>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @ApiModelProperty(value = "")
  public List<String> getTags() {
    return tags;
  }

  public void setTags(List<String> tags) {
    this.tags = tags;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComGithubJenkinsXJxPkgApisJenkinsIoV1Measurement comGithubJenkinsXJxPkgApisJenkinsIoV1Measurement = (ComGithubJenkinsXJxPkgApisJenkinsIoV1Measurement) o;
    return Objects.equals(this.measurementType, comGithubJenkinsXJxPkgApisJenkinsIoV1Measurement.measurementType) &&
        Objects.equals(this.measurementValue, comGithubJenkinsXJxPkgApisJenkinsIoV1Measurement.measurementValue) &&
        Objects.equals(this.name, comGithubJenkinsXJxPkgApisJenkinsIoV1Measurement.name) &&
        Objects.equals(this.tags, comGithubJenkinsXJxPkgApisJenkinsIoV1Measurement.tags);
  }

  @Override
  public int hashCode() {
    return Objects.hash(measurementType, measurementValue, name, tags);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComGithubJenkinsXJxPkgApisJenkinsIoV1Measurement {\n");
    
    sb.append("    measurementType: ").append(toIndentedString(measurementType)).append("\n");
    sb.append("    measurementValue: ").append(toIndentedString(measurementValue)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

