/*
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * StorageLocation
 */
@ApiModel(description = "StorageLocation")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-03-28T12:38:15.775957Z[Europe/London]")
public class ComGithubJenkinsXJxPkgApisJenkinsIoV1StorageLocation {
  public static final String SERIALIZED_NAME_BUCKET_URL = "bucketUrl";
  @SerializedName(SERIALIZED_NAME_BUCKET_URL)
  private String bucketUrl;

  public static final String SERIALIZED_NAME_CLASSIFIER = "classifier";
  @SerializedName(SERIALIZED_NAME_CLASSIFIER)
  private String classifier;

  public static final String SERIALIZED_NAME_GIT_BRANCH = "gitBranch";
  @SerializedName(SERIALIZED_NAME_GIT_BRANCH)
  private String gitBranch;

  public static final String SERIALIZED_NAME_GIT_URL = "gitUrl";
  @SerializedName(SERIALIZED_NAME_GIT_URL)
  private String gitUrl;

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1StorageLocation bucketUrl(String bucketUrl) {
    this.bucketUrl = bucketUrl;
    return this;
  }

   /**
   * Get bucketUrl
   * @return bucketUrl
  **/
  @ApiModelProperty(value = "")
  public String getBucketUrl() {
    return bucketUrl;
  }

  public void setBucketUrl(String bucketUrl) {
    this.bucketUrl = bucketUrl;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1StorageLocation classifier(String classifier) {
    this.classifier = classifier;
    return this;
  }

   /**
   * Get classifier
   * @return classifier
  **/
  @ApiModelProperty(value = "")
  public String getClassifier() {
    return classifier;
  }

  public void setClassifier(String classifier) {
    this.classifier = classifier;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1StorageLocation gitBranch(String gitBranch) {
    this.gitBranch = gitBranch;
    return this;
  }

   /**
   * Get gitBranch
   * @return gitBranch
  **/
  @ApiModelProperty(value = "")
  public String getGitBranch() {
    return gitBranch;
  }

  public void setGitBranch(String gitBranch) {
    this.gitBranch = gitBranch;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1StorageLocation gitUrl(String gitUrl) {
    this.gitUrl = gitUrl;
    return this;
  }

   /**
   * Get gitUrl
   * @return gitUrl
  **/
  @ApiModelProperty(value = "")
  public String getGitUrl() {
    return gitUrl;
  }

  public void setGitUrl(String gitUrl) {
    this.gitUrl = gitUrl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComGithubJenkinsXJxPkgApisJenkinsIoV1StorageLocation comGithubJenkinsXJxPkgApisJenkinsIoV1StorageLocation = (ComGithubJenkinsXJxPkgApisJenkinsIoV1StorageLocation) o;
    return Objects.equals(this.bucketUrl, comGithubJenkinsXJxPkgApisJenkinsIoV1StorageLocation.bucketUrl) &&
        Objects.equals(this.classifier, comGithubJenkinsXJxPkgApisJenkinsIoV1StorageLocation.classifier) &&
        Objects.equals(this.gitBranch, comGithubJenkinsXJxPkgApisJenkinsIoV1StorageLocation.gitBranch) &&
        Objects.equals(this.gitUrl, comGithubJenkinsXJxPkgApisJenkinsIoV1StorageLocation.gitUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bucketUrl, classifier, gitBranch, gitUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComGithubJenkinsXJxPkgApisJenkinsIoV1StorageLocation {\n");
    
    sb.append("    bucketUrl: ").append(toIndentedString(bucketUrl)).append("\n");
    sb.append("    classifier: ").append(toIndentedString(classifier)).append("\n");
    sb.append("    gitBranch: ").append(toIndentedString(gitBranch)).append("\n");
    sb.append("    gitUrl: ").append(toIndentedString(gitUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

