/*
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * PromotePullRequestStep is the step for promoting a version to an environment by raising a Pull Request on the git repository of the environment
 */
@ApiModel(description = "PromotePullRequestStep is the step for promoting a version to an environment by raising a Pull Request on the git repository of the environment")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-03-28T12:38:15.775957Z[Europe/London]")
public class ComGithubJenkinsXJxPkgApisJenkinsIoV1PromotePullRequestStep {
  public static final String SERIALIZED_NAME_COMPLETED_TIMESTAMP = "completedTimestamp";
  @SerializedName(SERIALIZED_NAME_COMPLETED_TIMESTAMP)
  private OffsetDateTime completedTimestamp;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_MERGE_COMMIT_S_H_A = "mergeCommitSHA";
  @SerializedName(SERIALIZED_NAME_MERGE_COMMIT_S_H_A)
  private String mergeCommitSHA;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_PULL_REQUEST_U_R_L = "pullRequestURL";
  @SerializedName(SERIALIZED_NAME_PULL_REQUEST_U_R_L)
  private String pullRequestURL;

  public static final String SERIALIZED_NAME_STARTED_TIMESTAMP = "startedTimestamp";
  @SerializedName(SERIALIZED_NAME_STARTED_TIMESTAMP)
  private OffsetDateTime startedTimestamp;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PromotePullRequestStep completedTimestamp(OffsetDateTime completedTimestamp) {
    this.completedTimestamp = completedTimestamp;
    return this;
  }

   /**
   * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
   * @return completedTimestamp
  **/
  @ApiModelProperty(value = "Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.")
  public OffsetDateTime getCompletedTimestamp() {
    return completedTimestamp;
  }

  public void setCompletedTimestamp(OffsetDateTime completedTimestamp) {
    this.completedTimestamp = completedTimestamp;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PromotePullRequestStep description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PromotePullRequestStep mergeCommitSHA(String mergeCommitSHA) {
    this.mergeCommitSHA = mergeCommitSHA;
    return this;
  }

   /**
   * Get mergeCommitSHA
   * @return mergeCommitSHA
  **/
  @ApiModelProperty(value = "")
  public String getMergeCommitSHA() {
    return mergeCommitSHA;
  }

  public void setMergeCommitSHA(String mergeCommitSHA) {
    this.mergeCommitSHA = mergeCommitSHA;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PromotePullRequestStep name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PromotePullRequestStep pullRequestURL(String pullRequestURL) {
    this.pullRequestURL = pullRequestURL;
    return this;
  }

   /**
   * Get pullRequestURL
   * @return pullRequestURL
  **/
  @ApiModelProperty(value = "")
  public String getPullRequestURL() {
    return pullRequestURL;
  }

  public void setPullRequestURL(String pullRequestURL) {
    this.pullRequestURL = pullRequestURL;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PromotePullRequestStep startedTimestamp(OffsetDateTime startedTimestamp) {
    this.startedTimestamp = startedTimestamp;
    return this;
  }

   /**
   * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
   * @return startedTimestamp
  **/
  @ApiModelProperty(value = "Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.")
  public OffsetDateTime getStartedTimestamp() {
    return startedTimestamp;
  }

  public void setStartedTimestamp(OffsetDateTime startedTimestamp) {
    this.startedTimestamp = startedTimestamp;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PromotePullRequestStep status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComGithubJenkinsXJxPkgApisJenkinsIoV1PromotePullRequestStep comGithubJenkinsXJxPkgApisJenkinsIoV1PromotePullRequestStep = (ComGithubJenkinsXJxPkgApisJenkinsIoV1PromotePullRequestStep) o;
    return Objects.equals(this.completedTimestamp, comGithubJenkinsXJxPkgApisJenkinsIoV1PromotePullRequestStep.completedTimestamp) &&
        Objects.equals(this.description, comGithubJenkinsXJxPkgApisJenkinsIoV1PromotePullRequestStep.description) &&
        Objects.equals(this.mergeCommitSHA, comGithubJenkinsXJxPkgApisJenkinsIoV1PromotePullRequestStep.mergeCommitSHA) &&
        Objects.equals(this.name, comGithubJenkinsXJxPkgApisJenkinsIoV1PromotePullRequestStep.name) &&
        Objects.equals(this.pullRequestURL, comGithubJenkinsXJxPkgApisJenkinsIoV1PromotePullRequestStep.pullRequestURL) &&
        Objects.equals(this.startedTimestamp, comGithubJenkinsXJxPkgApisJenkinsIoV1PromotePullRequestStep.startedTimestamp) &&
        Objects.equals(this.status, comGithubJenkinsXJxPkgApisJenkinsIoV1PromotePullRequestStep.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(completedTimestamp, description, mergeCommitSHA, name, pullRequestURL, startedTimestamp, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComGithubJenkinsXJxPkgApisJenkinsIoV1PromotePullRequestStep {\n");
    
    sb.append("    completedTimestamp: ").append(toIndentedString(completedTimestamp)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    mergeCommitSHA: ").append(toIndentedString(mergeCommitSHA)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    pullRequestURL: ").append(toIndentedString(pullRequestURL)).append("\n");
    sb.append("    startedTimestamp: ").append(toIndentedString(startedTimestamp)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

