/*
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Binary provies the details of a downloadable binary
 */
@ApiModel(description = "Binary provies the details of a downloadable binary")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-03-28T12:38:15.775957Z[Europe/London]")
public class ComGithubJenkinsXJxPkgApisJenkinsIoV1Binary {
  public static final String SERIALIZED_NAME_GOARCH = "goarch";
  @SerializedName(SERIALIZED_NAME_GOARCH)
  private String goarch;

  public static final String SERIALIZED_NAME_GOOS = "goos";
  @SerializedName(SERIALIZED_NAME_GOOS)
  private String goos;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  private String url;

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1Binary goarch(String goarch) {
    this.goarch = goarch;
    return this;
  }

   /**
   * Get goarch
   * @return goarch
  **/
  @ApiModelProperty(value = "")
  public String getGoarch() {
    return goarch;
  }

  public void setGoarch(String goarch) {
    this.goarch = goarch;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1Binary goos(String goos) {
    this.goos = goos;
    return this;
  }

   /**
   * Get goos
   * @return goos
  **/
  @ApiModelProperty(value = "")
  public String getGoos() {
    return goos;
  }

  public void setGoos(String goos) {
    this.goos = goos;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1Binary url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @ApiModelProperty(value = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComGithubJenkinsXJxPkgApisJenkinsIoV1Binary comGithubJenkinsXJxPkgApisJenkinsIoV1Binary = (ComGithubJenkinsXJxPkgApisJenkinsIoV1Binary) o;
    return Objects.equals(this.goarch, comGithubJenkinsXJxPkgApisJenkinsIoV1Binary.goarch) &&
        Objects.equals(this.goos, comGithubJenkinsXJxPkgApisJenkinsIoV1Binary.goos) &&
        Objects.equals(this.url, comGithubJenkinsXJxPkgApisJenkinsIoV1Binary.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(goarch, goos, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComGithubJenkinsXJxPkgApisJenkinsIoV1Binary {\n");
    
    sb.append("    goarch: ").append(toIndentedString(goarch)).append("\n");
    sb.append("    goos: ").append(toIndentedString(goos)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

