/*
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.ComGithubJenkinsXJxPkgApisJenkinsIoV1IssueLabel;
import org.openapitools.client.model.ComGithubJenkinsXJxPkgApisJenkinsIoV1UserDetails;
import org.threeten.bp.OffsetDateTime;

/**
 * IssueSummary is the summary of an issue
 */
@ApiModel(description = "IssueSummary is the summary of an issue")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-03-28T12:38:15.775957Z[Europe/London]")
public class ComGithubJenkinsXJxPkgApisJenkinsIoV1IssueSummary {
  public static final String SERIALIZED_NAME_ASSIGNEES = "assignees";
  @SerializedName(SERIALIZED_NAME_ASSIGNEES)
  private List<ComGithubJenkinsXJxPkgApisJenkinsIoV1UserDetails> assignees = null;

  public static final String SERIALIZED_NAME_BODY = "body";
  @SerializedName(SERIALIZED_NAME_BODY)
  private String body;

  public static final String SERIALIZED_NAME_CLOSED_BY = "closedBy";
  @SerializedName(SERIALIZED_NAME_CLOSED_BY)
  private ComGithubJenkinsXJxPkgApisJenkinsIoV1UserDetails closedBy = null;

  public static final String SERIALIZED_NAME_CREATION_TIMESTAMP = "creationTimestamp";
  @SerializedName(SERIALIZED_NAME_CREATION_TIMESTAMP)
  private OffsetDateTime creationTimestamp;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_LABELS = "labels";
  @SerializedName(SERIALIZED_NAME_LABELS)
  private List<ComGithubJenkinsXJxPkgApisJenkinsIoV1IssueLabel> labels = null;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  private String message;

  public static final String SERIALIZED_NAME_STATE = "state";
  @SerializedName(SERIALIZED_NAME_STATE)
  private String state;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  private String title;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  private String url;

  public static final String SERIALIZED_NAME_USER = "user";
  @SerializedName(SERIALIZED_NAME_USER)
  private ComGithubJenkinsXJxPkgApisJenkinsIoV1UserDetails user = null;

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1IssueSummary assignees(List<ComGithubJenkinsXJxPkgApisJenkinsIoV1UserDetails> assignees) {
    this.assignees = assignees;
    return this;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1IssueSummary addAssigneesItem(ComGithubJenkinsXJxPkgApisJenkinsIoV1UserDetails assigneesItem) {
    if (this.assignees == null) {
      this.assignees = new ArrayList<ComGithubJenkinsXJxPkgApisJenkinsIoV1UserDetails>();
    }
    this.assignees.add(assigneesItem);
    return this;
  }

   /**
   * Get assignees
   * @return assignees
  **/
  @ApiModelProperty(value = "")
  public List<ComGithubJenkinsXJxPkgApisJenkinsIoV1UserDetails> getAssignees() {
    return assignees;
  }

  public void setAssignees(List<ComGithubJenkinsXJxPkgApisJenkinsIoV1UserDetails> assignees) {
    this.assignees = assignees;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1IssueSummary body(String body) {
    this.body = body;
    return this;
  }

   /**
   * Get body
   * @return body
  **/
  @ApiModelProperty(value = "")
  public String getBody() {
    return body;
  }

  public void setBody(String body) {
    this.body = body;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1IssueSummary closedBy(ComGithubJenkinsXJxPkgApisJenkinsIoV1UserDetails closedBy) {
    this.closedBy = closedBy;
    return this;
  }

   /**
   * Get closedBy
   * @return closedBy
  **/
  @ApiModelProperty(value = "")
  public ComGithubJenkinsXJxPkgApisJenkinsIoV1UserDetails getClosedBy() {
    return closedBy;
  }

  public void setClosedBy(ComGithubJenkinsXJxPkgApisJenkinsIoV1UserDetails closedBy) {
    this.closedBy = closedBy;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1IssueSummary creationTimestamp(OffsetDateTime creationTimestamp) {
    this.creationTimestamp = creationTimestamp;
    return this;
  }

   /**
   * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
   * @return creationTimestamp
  **/
  @ApiModelProperty(value = "Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.")
  public OffsetDateTime getCreationTimestamp() {
    return creationTimestamp;
  }

  public void setCreationTimestamp(OffsetDateTime creationTimestamp) {
    this.creationTimestamp = creationTimestamp;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1IssueSummary id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1IssueSummary labels(List<ComGithubJenkinsXJxPkgApisJenkinsIoV1IssueLabel> labels) {
    this.labels = labels;
    return this;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1IssueSummary addLabelsItem(ComGithubJenkinsXJxPkgApisJenkinsIoV1IssueLabel labelsItem) {
    if (this.labels == null) {
      this.labels = new ArrayList<ComGithubJenkinsXJxPkgApisJenkinsIoV1IssueLabel>();
    }
    this.labels.add(labelsItem);
    return this;
  }

   /**
   * Get labels
   * @return labels
  **/
  @ApiModelProperty(value = "")
  public List<ComGithubJenkinsXJxPkgApisJenkinsIoV1IssueLabel> getLabels() {
    return labels;
  }

  public void setLabels(List<ComGithubJenkinsXJxPkgApisJenkinsIoV1IssueLabel> labels) {
    this.labels = labels;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1IssueSummary message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  @ApiModelProperty(value = "")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1IssueSummary state(String state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @ApiModelProperty(value = "")
  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1IssueSummary title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @ApiModelProperty(value = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1IssueSummary url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @ApiModelProperty(value = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1IssueSummary user(ComGithubJenkinsXJxPkgApisJenkinsIoV1UserDetails user) {
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  @ApiModelProperty(value = "")
  public ComGithubJenkinsXJxPkgApisJenkinsIoV1UserDetails getUser() {
    return user;
  }

  public void setUser(ComGithubJenkinsXJxPkgApisJenkinsIoV1UserDetails user) {
    this.user = user;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComGithubJenkinsXJxPkgApisJenkinsIoV1IssueSummary comGithubJenkinsXJxPkgApisJenkinsIoV1IssueSummary = (ComGithubJenkinsXJxPkgApisJenkinsIoV1IssueSummary) o;
    return Objects.equals(this.assignees, comGithubJenkinsXJxPkgApisJenkinsIoV1IssueSummary.assignees) &&
        Objects.equals(this.body, comGithubJenkinsXJxPkgApisJenkinsIoV1IssueSummary.body) &&
        Objects.equals(this.closedBy, comGithubJenkinsXJxPkgApisJenkinsIoV1IssueSummary.closedBy) &&
        Objects.equals(this.creationTimestamp, comGithubJenkinsXJxPkgApisJenkinsIoV1IssueSummary.creationTimestamp) &&
        Objects.equals(this.id, comGithubJenkinsXJxPkgApisJenkinsIoV1IssueSummary.id) &&
        Objects.equals(this.labels, comGithubJenkinsXJxPkgApisJenkinsIoV1IssueSummary.labels) &&
        Objects.equals(this.message, comGithubJenkinsXJxPkgApisJenkinsIoV1IssueSummary.message) &&
        Objects.equals(this.state, comGithubJenkinsXJxPkgApisJenkinsIoV1IssueSummary.state) &&
        Objects.equals(this.title, comGithubJenkinsXJxPkgApisJenkinsIoV1IssueSummary.title) &&
        Objects.equals(this.url, comGithubJenkinsXJxPkgApisJenkinsIoV1IssueSummary.url) &&
        Objects.equals(this.user, comGithubJenkinsXJxPkgApisJenkinsIoV1IssueSummary.user);
  }

  @Override
  public int hashCode() {
    return Objects.hash(assignees, body, closedBy, creationTimestamp, id, labels, message, state, title, url, user);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComGithubJenkinsXJxPkgApisJenkinsIoV1IssueSummary {\n");
    
    sb.append("    assignees: ").append(toIndentedString(assignees)).append("\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("    closedBy: ").append(toIndentedString(closedBy)).append("\n");
    sb.append("    creationTimestamp: ").append(toIndentedString(creationTimestamp)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

