/*
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.ComGithubJenkinsXJxPkgApisJenkinsIoV1PreviewActivityStep;
import org.openapitools.client.model.ComGithubJenkinsXJxPkgApisJenkinsIoV1PromoteActivityStep;
import org.openapitools.client.model.ComGithubJenkinsXJxPkgApisJenkinsIoV1StageActivityStep;

/**
 * PipelineActivityStep represents a step in a pipeline activity
 */
@ApiModel(description = "PipelineActivityStep represents a step in a pipeline activity")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-03-28T12:38:15.775957Z[Europe/London]")
public class ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineActivityStep {
  public static final String SERIALIZED_NAME_KIND = "kind";
  @SerializedName(SERIALIZED_NAME_KIND)
  private String kind;

  public static final String SERIALIZED_NAME_PREVIEW = "preview";
  @SerializedName(SERIALIZED_NAME_PREVIEW)
  private ComGithubJenkinsXJxPkgApisJenkinsIoV1PreviewActivityStep preview = null;

  public static final String SERIALIZED_NAME_PROMOTE = "promote";
  @SerializedName(SERIALIZED_NAME_PROMOTE)
  private ComGithubJenkinsXJxPkgApisJenkinsIoV1PromoteActivityStep promote = null;

  public static final String SERIALIZED_NAME_STAGE = "stage";
  @SerializedName(SERIALIZED_NAME_STAGE)
  private ComGithubJenkinsXJxPkgApisJenkinsIoV1StageActivityStep stage = null;

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineActivityStep kind(String kind) {
    this.kind = kind;
    return this;
  }

   /**
   * Get kind
   * @return kind
  **/
  @ApiModelProperty(value = "")
  public String getKind() {
    return kind;
  }

  public void setKind(String kind) {
    this.kind = kind;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineActivityStep preview(ComGithubJenkinsXJxPkgApisJenkinsIoV1PreviewActivityStep preview) {
    this.preview = preview;
    return this;
  }

   /**
   * Get preview
   * @return preview
  **/
  @ApiModelProperty(value = "")
  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PreviewActivityStep getPreview() {
    return preview;
  }

  public void setPreview(ComGithubJenkinsXJxPkgApisJenkinsIoV1PreviewActivityStep preview) {
    this.preview = preview;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineActivityStep promote(ComGithubJenkinsXJxPkgApisJenkinsIoV1PromoteActivityStep promote) {
    this.promote = promote;
    return this;
  }

   /**
   * Get promote
   * @return promote
  **/
  @ApiModelProperty(value = "")
  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PromoteActivityStep getPromote() {
    return promote;
  }

  public void setPromote(ComGithubJenkinsXJxPkgApisJenkinsIoV1PromoteActivityStep promote) {
    this.promote = promote;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineActivityStep stage(ComGithubJenkinsXJxPkgApisJenkinsIoV1StageActivityStep stage) {
    this.stage = stage;
    return this;
  }

   /**
   * Get stage
   * @return stage
  **/
  @ApiModelProperty(value = "")
  public ComGithubJenkinsXJxPkgApisJenkinsIoV1StageActivityStep getStage() {
    return stage;
  }

  public void setStage(ComGithubJenkinsXJxPkgApisJenkinsIoV1StageActivityStep stage) {
    this.stage = stage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineActivityStep comGithubJenkinsXJxPkgApisJenkinsIoV1PipelineActivityStep = (ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineActivityStep) o;
    return Objects.equals(this.kind, comGithubJenkinsXJxPkgApisJenkinsIoV1PipelineActivityStep.kind) &&
        Objects.equals(this.preview, comGithubJenkinsXJxPkgApisJenkinsIoV1PipelineActivityStep.preview) &&
        Objects.equals(this.promote, comGithubJenkinsXJxPkgApisJenkinsIoV1PipelineActivityStep.promote) &&
        Objects.equals(this.stage, comGithubJenkinsXJxPkgApisJenkinsIoV1PipelineActivityStep.stage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(kind, preview, promote, stage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineActivityStep {\n");
    
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    preview: ").append(toIndentedString(preview)).append("\n");
    sb.append("    promote: ").append(toIndentedString(promote)).append("\n");
    sb.append("    stage: ").append(toIndentedString(stage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

