/*
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionParameter;

/**
 * ExtensionSpec provides details of an extension available for a team
 */
@ApiModel(description = "ExtensionSpec provides details of an extension available for a team")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-03-28T12:38:15.775957Z[Europe/London]")
public class ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionSpec {
  public static final String SERIALIZED_NAME_CHILDREN = "children";
  @SerializedName(SERIALIZED_NAME_CHILDREN)
  private List<String> children = null;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_GIVEN = "given";
  @SerializedName(SERIALIZED_NAME_GIVEN)
  private String given;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_NAMESPACE = "namespace";
  @SerializedName(SERIALIZED_NAME_NAMESPACE)
  private String namespace;

  public static final String SERIALIZED_NAME_PARAMETERS = "parameters";
  @SerializedName(SERIALIZED_NAME_PARAMETERS)
  private List<ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionParameter> parameters = null;

  public static final String SERIALIZED_NAME_SCRIPT = "script";
  @SerializedName(SERIALIZED_NAME_SCRIPT)
  private String script;

  public static final String SERIALIZED_NAME_UUID = "uuid";
  @SerializedName(SERIALIZED_NAME_UUID)
  private String uuid;

  public static final String SERIALIZED_NAME_VERSION = "version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  private String version;

  public static final String SERIALIZED_NAME_WHEN = "when";
  @SerializedName(SERIALIZED_NAME_WHEN)
  private List<String> when = null;

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionSpec children(List<String> children) {
    this.children = children;
    return this;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionSpec addChildrenItem(String childrenItem) {
    if (this.children == null) {
      this.children = new ArrayList<String>();
    }
    this.children.add(childrenItem);
    return this;
  }

   /**
   * Get children
   * @return children
  **/
  @ApiModelProperty(value = "")
  public List<String> getChildren() {
    return children;
  }

  public void setChildren(List<String> children) {
    this.children = children;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionSpec description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionSpec given(String given) {
    this.given = given;
    return this;
  }

   /**
   * Get given
   * @return given
  **/
  @ApiModelProperty(value = "")
  public String getGiven() {
    return given;
  }

  public void setGiven(String given) {
    this.given = given;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionSpec name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionSpec namespace(String namespace) {
    this.namespace = namespace;
    return this;
  }

   /**
   * Get namespace
   * @return namespace
  **/
  @ApiModelProperty(value = "")
  public String getNamespace() {
    return namespace;
  }

  public void setNamespace(String namespace) {
    this.namespace = namespace;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionSpec parameters(List<ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionParameter> parameters) {
    this.parameters = parameters;
    return this;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionSpec addParametersItem(ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionParameter parametersItem) {
    if (this.parameters == null) {
      this.parameters = new ArrayList<ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionParameter>();
    }
    this.parameters.add(parametersItem);
    return this;
  }

   /**
   * Get parameters
   * @return parameters
  **/
  @ApiModelProperty(value = "")
  public List<ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionParameter> getParameters() {
    return parameters;
  }

  public void setParameters(List<ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionParameter> parameters) {
    this.parameters = parameters;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionSpec script(String script) {
    this.script = script;
    return this;
  }

   /**
   * Get script
   * @return script
  **/
  @ApiModelProperty(value = "")
  public String getScript() {
    return script;
  }

  public void setScript(String script) {
    this.script = script;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionSpec uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * Get uuid
   * @return uuid
  **/
  @ApiModelProperty(value = "")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionSpec version(String version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @ApiModelProperty(value = "")
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionSpec when(List<String> when) {
    this.when = when;
    return this;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionSpec addWhenItem(String whenItem) {
    if (this.when == null) {
      this.when = new ArrayList<String>();
    }
    this.when.add(whenItem);
    return this;
  }

   /**
   * Get when
   * @return when
  **/
  @ApiModelProperty(value = "")
  public List<String> getWhen() {
    return when;
  }

  public void setWhen(List<String> when) {
    this.when = when;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionSpec comGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionSpec = (ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionSpec) o;
    return Objects.equals(this.children, comGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionSpec.children) &&
        Objects.equals(this.description, comGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionSpec.description) &&
        Objects.equals(this.given, comGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionSpec.given) &&
        Objects.equals(this.name, comGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionSpec.name) &&
        Objects.equals(this.namespace, comGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionSpec.namespace) &&
        Objects.equals(this.parameters, comGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionSpec.parameters) &&
        Objects.equals(this.script, comGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionSpec.script) &&
        Objects.equals(this.uuid, comGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionSpec.uuid) &&
        Objects.equals(this.version, comGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionSpec.version) &&
        Objects.equals(this.when, comGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionSpec.when);
  }

  @Override
  public int hashCode() {
    return Objects.hash(children, description, given, name, namespace, parameters, script, uuid, version, when);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionSpec {\n");
    
    sb.append("    children: ").append(toIndentedString(children)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    given: ").append(toIndentedString(given)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    namespace: ").append(toIndentedString(namespace)).append("\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("    script: ").append(toIndentedString(script)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    when: ").append(toIndentedString(when)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

