/*
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * PipelineStructureStage contains the stage&#39;s name, one of either a reference to the Task corresponding to the stage if it has steps, a list of sequential stage names nested within this stage, or a list of parallel stage names nested within this stage, and information on this stage&#39;s depth within the PipelineStructure as a whole, the name of its parent stage, if any, the name of the stage before it in execution order, if any, and the name of the stage after it in execution order, if any.
 */
@ApiModel(description = "PipelineStructureStage contains the stage's name, one of either a reference to the Task corresponding to the stage if it has steps, a list of sequential stage names nested within this stage, or a list of parallel stage names nested within this stage, and information on this stage's depth within the PipelineStructure as a whole, the name of its parent stage, if any, the name of the stage before it in execution order, if any, and the name of the stage after it in execution order, if any.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-03-28T12:38:15.775957Z[Europe/London]")
public class ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructureStage {
  public static final String SERIALIZED_NAME_DEPTH = "depth";
  @SerializedName(SERIALIZED_NAME_DEPTH)
  private Integer depth;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_NEXT = "next";
  @SerializedName(SERIALIZED_NAME_NEXT)
  private String next;

  public static final String SERIALIZED_NAME_PARALLEL = "parallel";
  @SerializedName(SERIALIZED_NAME_PARALLEL)
  private List<String> parallel = null;

  public static final String SERIALIZED_NAME_PARENT = "parent";
  @SerializedName(SERIALIZED_NAME_PARENT)
  private String parent;

  public static final String SERIALIZED_NAME_PREVIOUS = "previous";
  @SerializedName(SERIALIZED_NAME_PREVIOUS)
  private String previous;

  public static final String SERIALIZED_NAME_STAGES = "stages";
  @SerializedName(SERIALIZED_NAME_STAGES)
  private List<String> stages = null;

  public static final String SERIALIZED_NAME_TASK_REF = "taskRef";
  @SerializedName(SERIALIZED_NAME_TASK_REF)
  private String taskRef;

  public static final String SERIALIZED_NAME_TASK_RUN_REF = "taskRunRef";
  @SerializedName(SERIALIZED_NAME_TASK_RUN_REF)
  private String taskRunRef;

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructureStage depth(Integer depth) {
    this.depth = depth;
    return this;
  }

   /**
   * Get depth
   * @return depth
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getDepth() {
    return depth;
  }

  public void setDepth(Integer depth) {
    this.depth = depth;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructureStage name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructureStage next(String next) {
    this.next = next;
    return this;
  }

   /**
   * Get next
   * @return next
  **/
  @ApiModelProperty(value = "")
  public String getNext() {
    return next;
  }

  public void setNext(String next) {
    this.next = next;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructureStage parallel(List<String> parallel) {
    this.parallel = parallel;
    return this;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructureStage addParallelItem(String parallelItem) {
    if (this.parallel == null) {
      this.parallel = new ArrayList<String>();
    }
    this.parallel.add(parallelItem);
    return this;
  }

   /**
   * Get parallel
   * @return parallel
  **/
  @ApiModelProperty(value = "")
  public List<String> getParallel() {
    return parallel;
  }

  public void setParallel(List<String> parallel) {
    this.parallel = parallel;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructureStage parent(String parent) {
    this.parent = parent;
    return this;
  }

   /**
   * Get parent
   * @return parent
  **/
  @ApiModelProperty(value = "")
  public String getParent() {
    return parent;
  }

  public void setParent(String parent) {
    this.parent = parent;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructureStage previous(String previous) {
    this.previous = previous;
    return this;
  }

   /**
   * Get previous
   * @return previous
  **/
  @ApiModelProperty(value = "")
  public String getPrevious() {
    return previous;
  }

  public void setPrevious(String previous) {
    this.previous = previous;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructureStage stages(List<String> stages) {
    this.stages = stages;
    return this;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructureStage addStagesItem(String stagesItem) {
    if (this.stages == null) {
      this.stages = new ArrayList<String>();
    }
    this.stages.add(stagesItem);
    return this;
  }

   /**
   * Get stages
   * @return stages
  **/
  @ApiModelProperty(value = "")
  public List<String> getStages() {
    return stages;
  }

  public void setStages(List<String> stages) {
    this.stages = stages;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructureStage taskRef(String taskRef) {
    this.taskRef = taskRef;
    return this;
  }

   /**
   * Must have one of TaskRef+TaskRunRef, Stages, or Parallel
   * @return taskRef
  **/
  @ApiModelProperty(value = "Must have one of TaskRef+TaskRunRef, Stages, or Parallel")
  public String getTaskRef() {
    return taskRef;
  }

  public void setTaskRef(String taskRef) {
    this.taskRef = taskRef;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructureStage taskRunRef(String taskRunRef) {
    this.taskRunRef = taskRunRef;
    return this;
  }

   /**
   * Populated during pod discovery, not at initial creation time.
   * @return taskRunRef
  **/
  @ApiModelProperty(value = "Populated during pod discovery, not at initial creation time.")
  public String getTaskRunRef() {
    return taskRunRef;
  }

  public void setTaskRunRef(String taskRunRef) {
    this.taskRunRef = taskRunRef;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructureStage comGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructureStage = (ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructureStage) o;
    return Objects.equals(this.depth, comGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructureStage.depth) &&
        Objects.equals(this.name, comGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructureStage.name) &&
        Objects.equals(this.next, comGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructureStage.next) &&
        Objects.equals(this.parallel, comGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructureStage.parallel) &&
        Objects.equals(this.parent, comGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructureStage.parent) &&
        Objects.equals(this.previous, comGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructureStage.previous) &&
        Objects.equals(this.stages, comGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructureStage.stages) &&
        Objects.equals(this.taskRef, comGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructureStage.taskRef) &&
        Objects.equals(this.taskRunRef, comGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructureStage.taskRunRef);
  }

  @Override
  public int hashCode() {
    return Objects.hash(depth, name, next, parallel, parent, previous, stages, taskRef, taskRunRef);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructureStage {\n");
    
    sb.append("    depth: ").append(toIndentedString(depth)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    next: ").append(toIndentedString(next)).append("\n");
    sb.append("    parallel: ").append(toIndentedString(parallel)).append("\n");
    sb.append("    parent: ").append(toIndentedString(parent)).append("\n");
    sb.append("    previous: ").append(toIndentedString(previous)).append("\n");
    sb.append("    stages: ").append(toIndentedString(stages)).append("\n");
    sb.append("    taskRef: ").append(toIndentedString(taskRef)).append("\n");
    sb.append("    taskRunRef: ").append(toIndentedString(taskRunRef)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

