/*
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * TeamStatus is the status for an Team resource
 */
@ApiModel(description = "TeamStatus is the status for an Team resource")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-03-28T12:38:15.775957Z[Europe/London]")
public class ComGithubJenkinsXJxPkgApisJenkinsIoV1TeamStatus {
  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  private String message;

  public static final String SERIALIZED_NAME_PROVISION_STATUS = "provisionStatus";
  @SerializedName(SERIALIZED_NAME_PROVISION_STATUS)
  private String provisionStatus;

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1TeamStatus message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  @ApiModelProperty(value = "")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1TeamStatus provisionStatus(String provisionStatus) {
    this.provisionStatus = provisionStatus;
    return this;
  }

   /**
   * Get provisionStatus
   * @return provisionStatus
  **/
  @ApiModelProperty(value = "")
  public String getProvisionStatus() {
    return provisionStatus;
  }

  public void setProvisionStatus(String provisionStatus) {
    this.provisionStatus = provisionStatus;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComGithubJenkinsXJxPkgApisJenkinsIoV1TeamStatus comGithubJenkinsXJxPkgApisJenkinsIoV1TeamStatus = (ComGithubJenkinsXJxPkgApisJenkinsIoV1TeamStatus) o;
    return Objects.equals(this.message, comGithubJenkinsXJxPkgApisJenkinsIoV1TeamStatus.message) &&
        Objects.equals(this.provisionStatus, comGithubJenkinsXJxPkgApisJenkinsIoV1TeamStatus.provisionStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(message, provisionStatus);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComGithubJenkinsXJxPkgApisJenkinsIoV1TeamStatus {\n");
    
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    provisionStatus: ").append(toIndentedString(provisionStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

