/*
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionDefinitionReference;

/**
 * ExtensionDefinitionReferenceList contains a list of ExtensionRepository items
 */
@ApiModel(description = "ExtensionDefinitionReferenceList contains a list of ExtensionRepository items")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-03-28T12:38:15.775957Z[Europe/London]")
public class ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionDefinitionReferenceList {
  public static final String SERIALIZED_NAME_REMOTES = "remotes";
  @SerializedName(SERIALIZED_NAME_REMOTES)
  private List<ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionDefinitionReference> remotes = new ArrayList<ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionDefinitionReference>();

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionDefinitionReferenceList remotes(List<ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionDefinitionReference> remotes) {
    this.remotes = remotes;
    return this;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionDefinitionReferenceList addRemotesItem(ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionDefinitionReference remotesItem) {
    this.remotes.add(remotesItem);
    return this;
  }

   /**
   * Get remotes
   * @return remotes
  **/
  @ApiModelProperty(required = true, value = "")
  public List<ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionDefinitionReference> getRemotes() {
    return remotes;
  }

  public void setRemotes(List<ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionDefinitionReference> remotes) {
    this.remotes = remotes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionDefinitionReferenceList comGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionDefinitionReferenceList = (ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionDefinitionReferenceList) o;
    return Objects.equals(this.remotes, comGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionDefinitionReferenceList.remotes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(remotes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComGithubJenkinsXJxPkgApisJenkinsIoV1ExtensionDefinitionReferenceList {\n");
    
    sb.append("    remotes: ").append(toIndentedString(remotes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

