/*
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.ComGithubJenkinsXJxPkgApisJenkinsIoV1PromoteWorkflowStep;
import org.openapitools.client.model.ComGithubJenkinsXJxPkgApisJenkinsIoV1WorkflowPreconditions;

/**
 * WorkflowStep represents a step in a pipeline activity
 */
@ApiModel(description = "WorkflowStep represents a step in a pipeline activity")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-03-28T12:38:15.775957Z[Europe/London]")
public class ComGithubJenkinsXJxPkgApisJenkinsIoV1WorkflowStep {
  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_KIND = "kind";
  @SerializedName(SERIALIZED_NAME_KIND)
  private String kind;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_PROMOTE = "promote";
  @SerializedName(SERIALIZED_NAME_PROMOTE)
  private ComGithubJenkinsXJxPkgApisJenkinsIoV1PromoteWorkflowStep promote = null;

  public static final String SERIALIZED_NAME_TRIGGER = "trigger";
  @SerializedName(SERIALIZED_NAME_TRIGGER)
  private ComGithubJenkinsXJxPkgApisJenkinsIoV1WorkflowPreconditions trigger = null;

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1WorkflowStep description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1WorkflowStep kind(String kind) {
    this.kind = kind;
    return this;
  }

   /**
   * Get kind
   * @return kind
  **/
  @ApiModelProperty(value = "")
  public String getKind() {
    return kind;
  }

  public void setKind(String kind) {
    this.kind = kind;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1WorkflowStep name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1WorkflowStep promote(ComGithubJenkinsXJxPkgApisJenkinsIoV1PromoteWorkflowStep promote) {
    this.promote = promote;
    return this;
  }

   /**
   * Get promote
   * @return promote
  **/
  @ApiModelProperty(value = "")
  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PromoteWorkflowStep getPromote() {
    return promote;
  }

  public void setPromote(ComGithubJenkinsXJxPkgApisJenkinsIoV1PromoteWorkflowStep promote) {
    this.promote = promote;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1WorkflowStep trigger(ComGithubJenkinsXJxPkgApisJenkinsIoV1WorkflowPreconditions trigger) {
    this.trigger = trigger;
    return this;
  }

   /**
   * Get trigger
   * @return trigger
  **/
  @ApiModelProperty(value = "")
  public ComGithubJenkinsXJxPkgApisJenkinsIoV1WorkflowPreconditions getTrigger() {
    return trigger;
  }

  public void setTrigger(ComGithubJenkinsXJxPkgApisJenkinsIoV1WorkflowPreconditions trigger) {
    this.trigger = trigger;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComGithubJenkinsXJxPkgApisJenkinsIoV1WorkflowStep comGithubJenkinsXJxPkgApisJenkinsIoV1WorkflowStep = (ComGithubJenkinsXJxPkgApisJenkinsIoV1WorkflowStep) o;
    return Objects.equals(this.description, comGithubJenkinsXJxPkgApisJenkinsIoV1WorkflowStep.description) &&
        Objects.equals(this.kind, comGithubJenkinsXJxPkgApisJenkinsIoV1WorkflowStep.kind) &&
        Objects.equals(this.name, comGithubJenkinsXJxPkgApisJenkinsIoV1WorkflowStep.name) &&
        Objects.equals(this.promote, comGithubJenkinsXJxPkgApisJenkinsIoV1WorkflowStep.promote) &&
        Objects.equals(this.trigger, comGithubJenkinsXJxPkgApisJenkinsIoV1WorkflowStep.trigger);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, kind, name, promote, trigger);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComGithubJenkinsXJxPkgApisJenkinsIoV1WorkflowStep {\n");
    
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    promote: ").append(toIndentedString(promote)).append("\n");
    sb.append("    trigger: ").append(toIndentedString(trigger)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

