/*
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineActivitySpec;
import org.openapitools.client.model.ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineActivityStatus;
import org.openapitools.client.model.IoK8sApimachineryPkgApisMetaV1ObjectMeta;

/**
 * PipelineActivity represents pipeline activity for a particular run of a pipeline
 */
@ApiModel(description = "PipelineActivity represents pipeline activity for a particular run of a pipeline")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-03-28T12:38:15.775957Z[Europe/London]")
public class ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineActivity {
  public static final String SERIALIZED_NAME_API_VERSION = "apiVersion";
  @SerializedName(SERIALIZED_NAME_API_VERSION)
  private String apiVersion;

  public static final String SERIALIZED_NAME_KIND = "kind";
  @SerializedName(SERIALIZED_NAME_KIND)
  private String kind;

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  private IoK8sApimachineryPkgApisMetaV1ObjectMeta metadata = null;

  public static final String SERIALIZED_NAME_SPEC = "spec";
  @SerializedName(SERIALIZED_NAME_SPEC)
  private ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineActivitySpec spec = null;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineActivityStatus status = null;

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineActivity apiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
    return this;
  }

   /**
   * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources
   * @return apiVersion
  **/
  @ApiModelProperty(value = "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources")
  public String getApiVersion() {
    return apiVersion;
  }

  public void setApiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineActivity kind(String kind) {
    this.kind = kind;
    return this;
  }

   /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds
   * @return kind
  **/
  @ApiModelProperty(value = "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds")
  public String getKind() {
    return kind;
  }

  public void setKind(String kind) {
    this.kind = kind;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineActivity metadata(IoK8sApimachineryPkgApisMetaV1ObjectMeta metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @ApiModelProperty(value = "")
  public IoK8sApimachineryPkgApisMetaV1ObjectMeta getMetadata() {
    return metadata;
  }

  public void setMetadata(IoK8sApimachineryPkgApisMetaV1ObjectMeta metadata) {
    this.metadata = metadata;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineActivity spec(ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineActivitySpec spec) {
    this.spec = spec;
    return this;
  }

   /**
   * Get spec
   * @return spec
  **/
  @ApiModelProperty(value = "")
  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineActivitySpec getSpec() {
    return spec;
  }

  public void setSpec(ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineActivitySpec spec) {
    this.spec = spec;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineActivity status(ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineActivityStatus status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineActivityStatus getStatus() {
    return status;
  }

  public void setStatus(ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineActivityStatus status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineActivity comGithubJenkinsXJxPkgApisJenkinsIoV1PipelineActivity = (ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineActivity) o;
    return Objects.equals(this.apiVersion, comGithubJenkinsXJxPkgApisJenkinsIoV1PipelineActivity.apiVersion) &&
        Objects.equals(this.kind, comGithubJenkinsXJxPkgApisJenkinsIoV1PipelineActivity.kind) &&
        Objects.equals(this.metadata, comGithubJenkinsXJxPkgApisJenkinsIoV1PipelineActivity.metadata) &&
        Objects.equals(this.spec, comGithubJenkinsXJxPkgApisJenkinsIoV1PipelineActivity.spec) &&
        Objects.equals(this.status, comGithubJenkinsXJxPkgApisJenkinsIoV1PipelineActivity.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apiVersion, kind, metadata, spec, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineActivity {\n");
    
    sb.append("    apiVersion: ").append(toIndentedString(apiVersion)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    spec: ").append(toIndentedString(spec)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

