/*
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructureStage;
import org.openapitools.client.model.IoK8sApimachineryPkgApisMetaV1ObjectMeta;

/**
 * PipelineStructure contains references to the Pipeline and PipelineRun, and a list of PipelineStructureStages in the pipeline. This allows us to map between a running Pod to its TaskRun, to the TaskRun&#39;s Task and PipelineRun, and finally from there to the stage and potential parent stages that the Pod is actually executing, for use with populating PipelineActivity and providing logs.
 */
@ApiModel(description = "PipelineStructure contains references to the Pipeline and PipelineRun, and a list of PipelineStructureStages in the pipeline. This allows us to map between a running Pod to its TaskRun, to the TaskRun's Task and PipelineRun, and finally from there to the stage and potential parent stages that the Pod is actually executing, for use with populating PipelineActivity and providing logs.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-03-28T12:38:15.775957Z[Europe/London]")
public class ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructure {
  public static final String SERIALIZED_NAME_API_VERSION = "apiVersion";
  @SerializedName(SERIALIZED_NAME_API_VERSION)
  private String apiVersion;

  public static final String SERIALIZED_NAME_KIND = "kind";
  @SerializedName(SERIALIZED_NAME_KIND)
  private String kind;

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  private IoK8sApimachineryPkgApisMetaV1ObjectMeta metadata = null;

  public static final String SERIALIZED_NAME_PIPELINE_REF = "pipelineRef";
  @SerializedName(SERIALIZED_NAME_PIPELINE_REF)
  private String pipelineRef;

  public static final String SERIALIZED_NAME_PIPELINE_RUN_REF = "pipelineRunRef";
  @SerializedName(SERIALIZED_NAME_PIPELINE_RUN_REF)
  private String pipelineRunRef;

  public static final String SERIALIZED_NAME_STAGES = "stages";
  @SerializedName(SERIALIZED_NAME_STAGES)
  private List<ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructureStage> stages = null;

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructure apiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
    return this;
  }

   /**
   * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources
   * @return apiVersion
  **/
  @ApiModelProperty(value = "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources")
  public String getApiVersion() {
    return apiVersion;
  }

  public void setApiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructure kind(String kind) {
    this.kind = kind;
    return this;
  }

   /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds
   * @return kind
  **/
  @ApiModelProperty(value = "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds")
  public String getKind() {
    return kind;
  }

  public void setKind(String kind) {
    this.kind = kind;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructure metadata(IoK8sApimachineryPkgApisMetaV1ObjectMeta metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @ApiModelProperty(value = "")
  public IoK8sApimachineryPkgApisMetaV1ObjectMeta getMetadata() {
    return metadata;
  }

  public void setMetadata(IoK8sApimachineryPkgApisMetaV1ObjectMeta metadata) {
    this.metadata = metadata;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructure pipelineRef(String pipelineRef) {
    this.pipelineRef = pipelineRef;
    return this;
  }

   /**
   * Get pipelineRef
   * @return pipelineRef
  **/
  @ApiModelProperty(required = true, value = "")
  public String getPipelineRef() {
    return pipelineRef;
  }

  public void setPipelineRef(String pipelineRef) {
    this.pipelineRef = pipelineRef;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructure pipelineRunRef(String pipelineRunRef) {
    this.pipelineRunRef = pipelineRunRef;
    return this;
  }

   /**
   * Get pipelineRunRef
   * @return pipelineRunRef
  **/
  @ApiModelProperty(required = true, value = "")
  public String getPipelineRunRef() {
    return pipelineRunRef;
  }

  public void setPipelineRunRef(String pipelineRunRef) {
    this.pipelineRunRef = pipelineRunRef;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructure stages(List<ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructureStage> stages) {
    this.stages = stages;
    return this;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructure addStagesItem(ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructureStage stagesItem) {
    if (this.stages == null) {
      this.stages = new ArrayList<ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructureStage>();
    }
    this.stages.add(stagesItem);
    return this;
  }

   /**
   * Get stages
   * @return stages
  **/
  @ApiModelProperty(value = "")
  public List<ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructureStage> getStages() {
    return stages;
  }

  public void setStages(List<ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructureStage> stages) {
    this.stages = stages;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructure comGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructure = (ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructure) o;
    return Objects.equals(this.apiVersion, comGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructure.apiVersion) &&
        Objects.equals(this.kind, comGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructure.kind) &&
        Objects.equals(this.metadata, comGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructure.metadata) &&
        Objects.equals(this.pipelineRef, comGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructure.pipelineRef) &&
        Objects.equals(this.pipelineRunRef, comGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructure.pipelineRunRef) &&
        Objects.equals(this.stages, comGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructure.stages);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apiVersion, kind, metadata, pipelineRef, pipelineRunRef, stages);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComGithubJenkinsXJxPkgApisJenkinsIoV1PipelineStructure {\n");
    
    sb.append("    apiVersion: ").append(toIndentedString(apiVersion)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    pipelineRef: ").append(toIndentedString(pipelineRef)).append("\n");
    sb.append("    pipelineRunRef: ").append(toIndentedString(pipelineRunRef)).append("\n");
    sb.append("    stages: ").append(toIndentedString(stages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

