/*
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SourceRepositorySpec provides details of the metadata for an App
 */
@ApiModel(description = "SourceRepositorySpec provides details of the metadata for an App")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-03-28T12:38:15.775957Z[Europe/London]")
public class ComGithubJenkinsXJxPkgApisJenkinsIoV1SourceRepositorySpec {
  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_ORG = "org";
  @SerializedName(SERIALIZED_NAME_ORG)
  private String org;

  public static final String SERIALIZED_NAME_PROVIDER = "provider";
  @SerializedName(SERIALIZED_NAME_PROVIDER)
  private String provider;

  public static final String SERIALIZED_NAME_REPO = "repo";
  @SerializedName(SERIALIZED_NAME_REPO)
  private String repo;

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1SourceRepositorySpec description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1SourceRepositorySpec org(String org) {
    this.org = org;
    return this;
  }

   /**
   * Get org
   * @return org
  **/
  @ApiModelProperty(value = "")
  public String getOrg() {
    return org;
  }

  public void setOrg(String org) {
    this.org = org;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1SourceRepositorySpec provider(String provider) {
    this.provider = provider;
    return this;
  }

   /**
   * Provider stores the URL of the git provider such as https://github.com
   * @return provider
  **/
  @ApiModelProperty(value = "Provider stores the URL of the git provider such as https://github.com")
  public String getProvider() {
    return provider;
  }

  public void setProvider(String provider) {
    this.provider = provider;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1SourceRepositorySpec repo(String repo) {
    this.repo = repo;
    return this;
  }

   /**
   * Get repo
   * @return repo
  **/
  @ApiModelProperty(value = "")
  public String getRepo() {
    return repo;
  }

  public void setRepo(String repo) {
    this.repo = repo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComGithubJenkinsXJxPkgApisJenkinsIoV1SourceRepositorySpec comGithubJenkinsXJxPkgApisJenkinsIoV1SourceRepositorySpec = (ComGithubJenkinsXJxPkgApisJenkinsIoV1SourceRepositorySpec) o;
    return Objects.equals(this.description, comGithubJenkinsXJxPkgApisJenkinsIoV1SourceRepositorySpec.description) &&
        Objects.equals(this.org, comGithubJenkinsXJxPkgApisJenkinsIoV1SourceRepositorySpec.org) &&
        Objects.equals(this.provider, comGithubJenkinsXJxPkgApisJenkinsIoV1SourceRepositorySpec.provider) &&
        Objects.equals(this.repo, comGithubJenkinsXJxPkgApisJenkinsIoV1SourceRepositorySpec.repo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, org, provider, repo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComGithubJenkinsXJxPkgApisJenkinsIoV1SourceRepositorySpec {\n");
    
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    org: ").append(toIndentedString(org)).append("\n");
    sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
    sb.append("    repo: ").append(toIndentedString(repo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

