/*
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.ComGithubJenkinsXJxPkgApisJenkinsIoV1CommitStatusDetails;

/**
 * CommitStatusSpec provides details of a particular commit status
 */
@ApiModel(description = "CommitStatusSpec provides details of a particular commit status")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-03-28T12:38:15.775957Z[Europe/London]")
public class ComGithubJenkinsXJxPkgApisJenkinsIoV1CommitStatusSpec {
  public static final String SERIALIZED_NAME_ITEMS = "items";
  @SerializedName(SERIALIZED_NAME_ITEMS)
  private List<ComGithubJenkinsXJxPkgApisJenkinsIoV1CommitStatusDetails> items = new ArrayList<ComGithubJenkinsXJxPkgApisJenkinsIoV1CommitStatusDetails>();

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1CommitStatusSpec items(List<ComGithubJenkinsXJxPkgApisJenkinsIoV1CommitStatusDetails> items) {
    this.items = items;
    return this;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1CommitStatusSpec addItemsItem(ComGithubJenkinsXJxPkgApisJenkinsIoV1CommitStatusDetails itemsItem) {
    this.items.add(itemsItem);
    return this;
  }

   /**
   * Get items
   * @return items
  **/
  @ApiModelProperty(required = true, value = "")
  public List<ComGithubJenkinsXJxPkgApisJenkinsIoV1CommitStatusDetails> getItems() {
    return items;
  }

  public void setItems(List<ComGithubJenkinsXJxPkgApisJenkinsIoV1CommitStatusDetails> items) {
    this.items = items;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComGithubJenkinsXJxPkgApisJenkinsIoV1CommitStatusSpec comGithubJenkinsXJxPkgApisJenkinsIoV1CommitStatusSpec = (ComGithubJenkinsXJxPkgApisJenkinsIoV1CommitStatusSpec) o;
    return Objects.equals(this.items, comGithubJenkinsXJxPkgApisJenkinsIoV1CommitStatusSpec.items);
  }

  @Override
  public int hashCode() {
    return Objects.hash(items);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComGithubJenkinsXJxPkgApisJenkinsIoV1CommitStatusSpec {\n");
    
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

