/*
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Statement represents a decision that was made, for example that a promotion was approved or denied
 */
@ApiModel(description = "Statement represents a decision that was made, for example that a promotion was approved or denied")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-03-28T12:38:15.775957Z[Europe/London]")
public class ComGithubJenkinsXJxPkgApisJenkinsIoV1Statement {
  public static final String SERIALIZED_NAME_MEASUREMENT_VALUE = "measurementValue";
  @SerializedName(SERIALIZED_NAME_MEASUREMENT_VALUE)
  private Boolean measurementValue;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_STATEMENT_TYPE = "statementType";
  @SerializedName(SERIALIZED_NAME_STATEMENT_TYPE)
  private String statementType;

  public static final String SERIALIZED_NAME_TAGS = "tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  private List<String> tags = null;

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1Statement measurementValue(Boolean measurementValue) {
    this.measurementValue = measurementValue;
    return this;
  }

   /**
   * Get measurementValue
   * @return measurementValue
  **/
  @ApiModelProperty(required = true, value = "")
  public Boolean getMeasurementValue() {
    return measurementValue;
  }

  public void setMeasurementValue(Boolean measurementValue) {
    this.measurementValue = measurementValue;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1Statement name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1Statement statementType(String statementType) {
    this.statementType = statementType;
    return this;
  }

   /**
   * Get statementType
   * @return statementType
  **/
  @ApiModelProperty(required = true, value = "")
  public String getStatementType() {
    return statementType;
  }

  public void setStatementType(String statementType) {
    this.statementType = statementType;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1Statement tags(List<String> tags) {
    this.tags = tags;
    return this;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1Statement addTagsItem(String tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<String>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @ApiModelProperty(value = "")
  public List<String> getTags() {
    return tags;
  }

  public void setTags(List<String> tags) {
    this.tags = tags;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComGithubJenkinsXJxPkgApisJenkinsIoV1Statement comGithubJenkinsXJxPkgApisJenkinsIoV1Statement = (ComGithubJenkinsXJxPkgApisJenkinsIoV1Statement) o;
    return Objects.equals(this.measurementValue, comGithubJenkinsXJxPkgApisJenkinsIoV1Statement.measurementValue) &&
        Objects.equals(this.name, comGithubJenkinsXJxPkgApisJenkinsIoV1Statement.name) &&
        Objects.equals(this.statementType, comGithubJenkinsXJxPkgApisJenkinsIoV1Statement.statementType) &&
        Objects.equals(this.tags, comGithubJenkinsXJxPkgApisJenkinsIoV1Statement.tags);
  }

  @Override
  public int hashCode() {
    return Objects.hash(measurementValue, name, statementType, tags);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComGithubJenkinsXJxPkgApisJenkinsIoV1Statement {\n");
    
    sb.append("    measurementValue: ").append(toIndentedString(measurementValue)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    statementType: ").append(toIndentedString(statementType)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

