/*
 * Jenkins X
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.ComGithubJenkinsXJxPkgApisJenkinsIoV1GitStatus;
import org.threeten.bp.OffsetDateTime;

/**
 * PromoteUpdateStep is the step for updating a promotion after the Pull Request merges to master
 */
@ApiModel(description = "PromoteUpdateStep is the step for updating a promotion after the Pull Request merges to master")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-03-28T12:38:15.775957Z[Europe/London]")
public class ComGithubJenkinsXJxPkgApisJenkinsIoV1PromoteUpdateStep {
  public static final String SERIALIZED_NAME_COMPLETED_TIMESTAMP = "completedTimestamp";
  @SerializedName(SERIALIZED_NAME_COMPLETED_TIMESTAMP)
  private OffsetDateTime completedTimestamp;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_STARTED_TIMESTAMP = "startedTimestamp";
  @SerializedName(SERIALIZED_NAME_STARTED_TIMESTAMP)
  private OffsetDateTime startedTimestamp;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public static final String SERIALIZED_NAME_STATUSES = "statuses";
  @SerializedName(SERIALIZED_NAME_STATUSES)
  private List<ComGithubJenkinsXJxPkgApisJenkinsIoV1GitStatus> statuses = null;

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PromoteUpdateStep completedTimestamp(OffsetDateTime completedTimestamp) {
    this.completedTimestamp = completedTimestamp;
    return this;
  }

   /**
   * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
   * @return completedTimestamp
  **/
  @ApiModelProperty(value = "Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.")
  public OffsetDateTime getCompletedTimestamp() {
    return completedTimestamp;
  }

  public void setCompletedTimestamp(OffsetDateTime completedTimestamp) {
    this.completedTimestamp = completedTimestamp;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PromoteUpdateStep description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PromoteUpdateStep name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PromoteUpdateStep startedTimestamp(OffsetDateTime startedTimestamp) {
    this.startedTimestamp = startedTimestamp;
    return this;
  }

   /**
   * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
   * @return startedTimestamp
  **/
  @ApiModelProperty(value = "Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.")
  public OffsetDateTime getStartedTimestamp() {
    return startedTimestamp;
  }

  public void setStartedTimestamp(OffsetDateTime startedTimestamp) {
    this.startedTimestamp = startedTimestamp;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PromoteUpdateStep status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PromoteUpdateStep statuses(List<ComGithubJenkinsXJxPkgApisJenkinsIoV1GitStatus> statuses) {
    this.statuses = statuses;
    return this;
  }

  public ComGithubJenkinsXJxPkgApisJenkinsIoV1PromoteUpdateStep addStatusesItem(ComGithubJenkinsXJxPkgApisJenkinsIoV1GitStatus statusesItem) {
    if (this.statuses == null) {
      this.statuses = new ArrayList<ComGithubJenkinsXJxPkgApisJenkinsIoV1GitStatus>();
    }
    this.statuses.add(statusesItem);
    return this;
  }

   /**
   * Get statuses
   * @return statuses
  **/
  @ApiModelProperty(value = "")
  public List<ComGithubJenkinsXJxPkgApisJenkinsIoV1GitStatus> getStatuses() {
    return statuses;
  }

  public void setStatuses(List<ComGithubJenkinsXJxPkgApisJenkinsIoV1GitStatus> statuses) {
    this.statuses = statuses;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComGithubJenkinsXJxPkgApisJenkinsIoV1PromoteUpdateStep comGithubJenkinsXJxPkgApisJenkinsIoV1PromoteUpdateStep = (ComGithubJenkinsXJxPkgApisJenkinsIoV1PromoteUpdateStep) o;
    return Objects.equals(this.completedTimestamp, comGithubJenkinsXJxPkgApisJenkinsIoV1PromoteUpdateStep.completedTimestamp) &&
        Objects.equals(this.description, comGithubJenkinsXJxPkgApisJenkinsIoV1PromoteUpdateStep.description) &&
        Objects.equals(this.name, comGithubJenkinsXJxPkgApisJenkinsIoV1PromoteUpdateStep.name) &&
        Objects.equals(this.startedTimestamp, comGithubJenkinsXJxPkgApisJenkinsIoV1PromoteUpdateStep.startedTimestamp) &&
        Objects.equals(this.status, comGithubJenkinsXJxPkgApisJenkinsIoV1PromoteUpdateStep.status) &&
        Objects.equals(this.statuses, comGithubJenkinsXJxPkgApisJenkinsIoV1PromoteUpdateStep.statuses);
  }

  @Override
  public int hashCode() {
    return Objects.hash(completedTimestamp, description, name, startedTimestamp, status, statuses);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComGithubJenkinsXJxPkgApisJenkinsIoV1PromoteUpdateStep {\n");
    
    sb.append("    completedTimestamp: ").append(toIndentedString(completedTimestamp)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    startedTimestamp: ").append(toIndentedString(startedTimestamp)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    statuses: ").append(toIndentedString(statuses)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

